# Generated by Django 5.2.2 on 2026-06-12 14:10

import cloudinary.models
import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('profile_pic', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('bio', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_requested', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('budget', models.CharField(choices=[('Under Ksh 5k', 'Under Ksh 5k'), ('Ksh 5k - 20k', 'Ksh 5k - 20k'), ('Ksh 20k - 50k', 'Ksh 20k - 50k'), ('Ksh 50k - 150k', 'Ksh 50k - 150k'), ('Ksh 150k - 500k', 'Ksh 150k - 500k'), ('Ksh 500k+', 'Ksh 500k+')], max_length=50)),
                ('details', models.TextField(help_text="The client's project vision")),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('contacted', 'Discovery Call Scheduled'), ('proposal', 'Proposal Sent'), ('won', 'Closed Won'), ('lost', 'Closed Lost')], default='pending', max_length=20)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', cloudinary.models.CloudinaryField(help_text='Upload a clean PNG with a transparent background', max_length=255, verbose_name='logo')),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='e.g., Cinematic Documentary Shoot', max_length=100)),
                ('client', models.CharField(blank=True, help_text='e.g., Northbound Coffee Co.', max_length=100)),
                ('category', models.CharField(choices=[('Best Moments', 'Best Moments'), ('Posters', 'Posters'), ('Samples', 'Samples')], default='Samples', max_length=50)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('is_featured', models.BooleanField(default=False, help_text='Show on the homepage grid?')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('excerpt', models.CharField(help_text='Short teaser for the service card', max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text="FontAwesome icon class (e.g., 'fa-video')", max_length=50)),
                ('image', cloudinary.models.CloudinaryField(blank=True, help_text='Large cinematic image for the Services page', max_length=255, null=True, verbose_name='image')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_subscribed', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(help_text='e.g., Amani Otieno', max_length=100)),
                ('role', models.CharField(help_text='e.g., Founder, Northbound Coffee', max_length=100)),
                ('quote', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceDeliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., '4K Drone Cinematography'", max_length=150)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='core.service')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('excerpt', models.TextField(help_text='Short summary for the article card', max_length=300)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content')),
                ('views', models.PositiveIntegerField(default=0)),
                ('read_time', models.PositiveIntegerField(default=5, help_text='Estimated read time in minutes')),
                ('is_published', models.BooleanField(default=False)),
                ('publish_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.author')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category')),
                ('tags', models.ManyToManyField(blank=True, to='core.tag')),
            ],
        ),
    ]
