# Generated by Django 5.2.2 on 2026-06-12 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='excerpt',
            new_name='tagline',
        ),
    ]
