# Generated by Django 5.2.2 on 2025-08-02 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_newslettersubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='device_target',
            field=models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('both', 'Both')], default='both', max_length=10),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='placement',
            field=models.CharField(choices=[('carousel', 'Carousel'), ('inline', 'Inline'), ('mobile', 'Mobile Bottom Banner')], default='inline', max_length=20),
        ),
        migrations.CreateModel(
            name='AdClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='core.advertisement')),
            ],
        ),
        migrations.CreateModel(
            name='AdView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='core.advertisement')),
            ],
        ),
    ]
