# Generated by Django 5.2.2 on 2026-06-23 16:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_post_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Portfolio Categories',
            },
        ),
        migrations.AlterField(
            model_name='booking',
            name='budget',
            field=models.CharField(choices=[('Under Ksh 5k', 'Under Ksh 5k'), ('Ksh 5k - 20k', 'Ksh 5k - 20k'), ('Ksh 20k - 50k', 'Ksh 20k - 50k'), ('Ksh 5k - 150k', 'Ksh 50k - 150k'), ('Ksh 150k - 500k', 'Ksh 150k - 500k'), ('Ksh 500k+', 'Ksh 500k+')], max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('contacted', 'Discovery Call Scheduled'), ('proposal', 'Proposal Sent'), ('won', 'Closed Won'), ('lost', 'Closed Lost')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='portfolioimage',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, help_text='Show on the homepage grid?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time the post goes live'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='portfolioimage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.portfoliocategory'),
        ),
    ]
