# Generated by Django 5.2.2 on 2025-08-05 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_advertisement_device_target_advertisement_placement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approved',
        ),
    ]
