# Generated by Django 5.2.2 on 2026-06-24 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_portfoliocategory_alter_booking_budget_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='URL friendly name (e.g., brand-launch)', unique=True)),
                ('client_name', models.CharField(max_length=200)),
                ('industry', models.CharField(max_length=100)),
                ('project_type', models.CharField(help_text='e.g., Cinematic Production, Branding', max_length=100)),
                ('challenge', models.TextField()),
                ('solution', models.TextField()),
                ('outcome', models.TextField()),
                ('hero_image', models.ImageField(upload_to='case_studies/')),
                ('featured', models.BooleanField(default=False, help_text='Show this as the massive hero case study')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Case Studies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseStudyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='e.g., 3.4M or +45%', max_length=50)),
                ('label', models.CharField(help_text='e.g., Impressions or Audience Growth', max_length=100)),
                ('case_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='core.casestudy')),
            ],
        ),
    ]
