# Generated by Django 5.2.2 on 2026-06-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_casestudy_casestudymetric'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='excerpt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
