# Generated by Django 5.2.2 on 2025-08-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_engagement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('expires', models.DateField()),
                ('link', models.URLField()),
            ],
        ),
    ]
