# Generated by Django 5.2.2 on 2026-06-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_portfolioimage_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioimage',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
