"""
Django settings for captainmedia project.

Generated by 'django-admin startproject' using Django 5.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
load_dotenv()
from django import db
import cloudinary
from cloudinary_storage.storage import MediaCloudinaryStorage
import os
from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
dotenv_path = BASE_DIR / '.env'
# settings.py

# 1. Load your environment variables strictly
load_dotenv(dotenv_path=BASE_DIR / '.env')

# 2. Setup SECRET_KEY with a fallback for local dev
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-dev-key-for-local-only')

# 3. Robust DEBUG logic
DEBUG = True
# 4. Correct ALLOWED_HOSTS logic
ALLOWED_HOSTS = ['*']
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',  # CORS headers for API
    'cloudinary',
    'django_filters',  # For filtering in DRF
    'cloudinary_storage',
    # 'django_q',  # Django-Q for background tasks
    'core.apps.CoreConfig',
    'django_ckeditor_5',  # ✅ correct name
  # CKEditor 5 for rich text editing
    ]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.common.CommonMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS middleware
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # For React dev
    "http://127.0.0.1:3000",
    "http://localhost:5173",  
    "http://localhost:8080",  # For Django dev
    "https://www.captain001media.co.ke",  # Replace with your deployed frontend domain
]

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

ROOT_URLCONF = 'captainmedia.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# # ==========================================
# # BACKGROUND TASK ENGINE (Django-Q)
# # ==========================================
# Q_CLUSTER = {
#     'name': 'captain_001_workers',
#     'workers': 4,             # 4 background threads working simultaneously
#     'recycle': 500,           # Refresh workers to prevent memory leaks
#     'timeout': 60,            # Max time an email has to send before timing out
#     'compress': True,         # Save database space
#     'cpu_affinity': 1,        
#     'save_limit': 250,        # Keep a history of the last 250 tasks
#     'queue_limit': 500,
#     'catch_up': False,
#     'orm': 'default'          # Use SQLite/Postgres as the message broker
# }

WSGI_APPLICATION = 'captainmedia.wsgi.application'

# settings.py - add this at the very bottom
# print(f"--- DEBUG: RESEND_API_KEY value is: '{os.environ.get('RESEND_API_KEY')}' ---")
# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
import os

import dj_database_url

# Make sure you replace [YOUR-PASSWORD] with the actual password you typed when you created this Supabase project.
# Do not include the brackets [ ].
# SUPABASE_URL = "postgresql://postgres:533dPLP1FilhMhwu@db.iotbcmzqjwklqlbdbfsx.supabase.co:5432/postgres"

# DATABASES = {
#     'default': dj_database_url.parse(
#         SUPABASE_URL,
#         conn_max_age=600,
#         conn_health_checks=True,
#     )
# }
DATABASES = {
    'default': dj_database_url.config(
        default=os.environ.get('SUPABASE_URL'),
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


cloudinary.config( 
  cloud_name = os.environ.get('CLOUDINARY_CLOUD_NAME'), 
  api_key = os.environ.get('CLOUDINARY_API_KEY'), 
  api_secret = os.environ.get('CLOUDINARY_API_SECRET')
)

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.environ.get('CLOUDINARY_API_KEY'),
    'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET'),
}




# settings.py
load_dotenv(dotenv_path=BASE_DIR / '.env')



# ==========================================
# 2. RESEND EMAIL CONFIGURATION
# ==========================================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.resend.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = 'resend'

# ==== EMAIL UPDATED ====
EMAIL_HOST_PASSWORD = os.environ.get('RESEND_API_KEY')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL')
AGENCY_ADMIN_EMAIL = os.environ.get('AGENCY_ADMIN_EMAIL')


ADMINS = [('Admin Name', 'admin@example.com')]

# CKEditor5
CKEDITOR_5_FILE_STORAGE = "cloudinary_storage.storage.MediaCloudinaryStorage"

CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': [
            'heading', '|',
            'bold', 'italic', 'link', 'imageUpload', 'blockQuote',
            '|', 'undo', 'redo'
        ],
        'height': 400,
        'width': '100%',
    }
}


REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 6,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ]
}


# settings.py
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

